name = "htmb"
version = "2.1.0"
gleam = ">= 0.32.0"
description = "A tiny HTML builder for Gleam"
licences = ["Apache-2.0"]

repository = { type = "github", user = "lpil", repo = "htmb" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
